spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fintech?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mnikingang$0609
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 300000  # 5 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true  # Pretty-print SQL in logs
server:
  port: 8080
logging:
  level:
    com.zaxxer.hikari: DEBUG  # Log HikariCP connection details