spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    driver-class-name: org.postgresql.Driver
    username: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 300000  # 5 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Pretty-print SQL in logs
server:
  port: 8080
logging:
  level:
    com.zaxxer.hikari: DEBUG  # Log HikariCP connection details